### ISSUE TITLE
Plugin "react-hooks" was conflicted

### ISSUE THREAD

**Issue by beterrabaA** [Rocketseat/eslint-config-rocketseat#13]
## A versão 1.3.0 da tendo conflito com eslint-config-next/core-web-vital no Next.JS
<img width="695" alt="Captura de tela 2023-07-09 213407" src="https://github.com/Rocketseat/eslint-config-rocketseat/assets/74778541/3107d3b6-47bf-417b-8ff0-d5349fb3783e">

## Minha importação no eslint.json 
<img width="506" alt="Captura de tela 2023-07-09 213714" src="https://github.com/Rocketseat/eslint-config-rocketseat/assets/74778541/9397e987-71b9-4325-b753-08ed0817bd91">

### Acabei resolvendo o problema apagando o plugin react-hoocks/recommended no react.js do pacote.

<img width="255" alt="Captura de tela 2023-07-09 214211" src="https://github.com/Rocketseat/eslint-config-rocketseat/assets/74778541/d307d7cc-6112-465f-a5be-e736ed85b7e0">
<img width="348" alt="Captura de tela 2023-07-09 214246" src="https://github.com/Rocketseat/eslint-config-rocketseat/assets/74778541/f514a502-8895-4121-ab74-823d51bf729a">

**Comment by lorenzoa7** [comment]
Mesma coisa acontecendo comigo aqui....

**Comment by Felipe8297** [comment]
mesma coisa por aqui 

atualização: parece que é algo com a nova versão do next, se der uma downgrade para "next": "13.4.7" e "eslint-config-next": "13.4.7", vai funcionar tudo normal

**Comment by samuelsilvati** [comment]
Como o Felipe disse é algo com a atualização do Next. Tive o mesmo problema.

**Comment by beterrabaA** [comment]
Parece que foi uma adição ou modificação no plugin do lint padrão do Next.Js,por isso o conflito.

**Comment by beterrabaA** [comment]
> mesma coisa por aqui 
> 
> atualização: parece que é algo com a nova versão do next, se der uma downgrade para "next": "13.4.7" e "eslint-config-next": "13.4.7", vai funcionar tudo normal

Não precisa do downgrade, só fazer o mesmo fix que funciona normal

**Comment by lorenzoa7** [comment]
> > mesma coisa por aqui
> > atualização: parece que é algo com a nova versão do next, se der uma downgrade para "next": "13.4.7" e "eslint-config-next": "13.4.7", vai funcionar tudo normal
> 
> Não precisa do downgrade, só fazer o mesmo fix que funciona normal

Como assim fazer o mesmo fix?

**Comment by gustavofbc** [comment]
Posso estar enganado, mas creio que ele repassou que você não vai precisar fazer o downgrade da versão, somente remover o plugin react-hoocks/recommended do arquivo react do pacote @rocketseat/eslint-config e já vai funcionar.

att: fiz o teste aqui e funcionou dessa forma

**Comment by beterrabaA** [comment]
> > > mesma coisa por aqui
> > > atualização: parece que é algo com a nova versão do next, se der uma downgrade para "next": "13.4.7" e "eslint-config-next": "13.4.7", vai funcionar tudo normal
> > 
> > Não precisa do downgrade, só fazer o mesmo fix que funciona normal
> 
> Como assim fazer o mesmo fix?

No diretório do pacote /node_modules/@rocketseat/eslint-config vai ter um arquivo "react.js" só fazer a modificação que tá sendo mostrada nas duas últimas imagens e o problema estará solucionado,sem downgrade. Da um reload no vscode.

**Comment by ndelanhese** [comment]
Same issue here, even after changing the lines in the node_modules, nothing has changed and it still doesn't work. Now the error says something like "prettier (startsWith) not found."

**Comment by lucasstsx** [comment]
> > > > mesma coisa por aqui 
> > > > atualização: parece que é algo com a nova versão do next, se der uma downgrade para "next": "13.4.7" e "eslint-config-next": "13.4.7", vai funcionar tudo normal
> > > 
> > > 
> > > Não precisa do downgrade, só faça o mesmo conserto que funciona normal
> > 
> > 
> > Como assim fazer o mesmo conserto?
> 
> No diretório do pacote /node_modules/@rocketseat/eslint-config vai ter um arquivo "react.js" só fazer a modificação que tá sendo mostrado nas duas últimas imagens e o problema será solucionado,sem downgrade. Da um reload no vscode.

Funcionou aqui, obrigado!
