### ISSUE TITLE
Configure tab width

### ISSUE THREAD

**Issue by ramonscampos** [Rocketseat/eslint-config-rocketseat#3]
I normally use the property tabWidth configurated in 4 spaces in VS Code. So I'm getting prettier/prettier error forcing me to use 2 spaces.

How do I configure this (and prettier options in general).

**Comment by bernardinorafael** [comment]
Fala @ramonscampos, beleza??

Você pode adicionar a seguinte configuração ao seu arquivo .eslintrc.json/js e vai te atender!!

Um abraço.

```
 rules: {
    'prettier/prettier': ["error", {
      'tabWidth': 4,
    }],
````

**Comment by bernardinorafael** [comment]
> I normally use the property tabWidth configurated in 4 spaces in VS Code. So I'm getting prettier/prettier error forcing me to use 2 spaces.
> 
> How do I configure this (and prettier options in general).

@ramonscampos, 

You can add the following configuration to your file .eslintrc.json/js.

See ya.

```
 rules: {
    'prettier/prettier': ["error", {
      'tabWidth': 4,
    }],
````

**Comment by diego3g** [comment]
As @bernardinorafael, you can override any config inside your eslint config file.
